# tomkeyLk ビルド設定
# This file defines the boards and shields for the build process

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config

include:
  - board: nice_nano_v2
    shield: tomkey_L
  - board: nice_nano_v2
    shield: tomkey_R
